version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=Asia/Jerusalem
    network_mode: host # Runs on port 32400
    volumes:
      - <path to>/plex/database:/config
      - <path to>/plex/transcode/temp:/transcode
      - <path to>/plex/data:/data

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - <path to>/sonarr/data:/config
      - <path to>/sonarr/tvseries:/tv
      - <path to>/torrent/downloadclient-downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - <path to>/radarr/data:/config
      - <path to>/radarr/movies:/movies
      - <path to>/torrent/downloadclient-downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - <path to>/bazarr/config:/config
      - <path to>/radarr/movies:/movies
      - <path to>/sonarr/tvseries:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - <path to>/jackett/data:/config
      - <path to>/jackett/blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  transmission:
    restart: always
    image: "dperson/transmission"
    container_name: transmission
    ports:
      - 9091:9091
    volumes:
      - <path to>/torrent/downloadclient-downloads:/var/lib/transmission-daemon

  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: plex.manjaro # set to fqdn of host
    ports:
      - 80:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
